Revert "sepolicy: address hal_fingerprint_default denial"
This reverts commit 87792089e866d5640fb656f2f12de9e70005e56a.

FAILED: //system/sepolicy:precompiled_sepolicy Compiling cil files for precompiled_sepolicy [common]
Outputs: /out/soong/.intermediates/system/sepolicy/precompiled_sepolicy/android_common/precompiled_sepolicy
Error: exited with code: 1
Command: /out/host/linux-x86/bin/secilc -m -M true -G -c 30 /out/soong/.intermediates/system/sepolicy/plat_sepolicy.cil/android_common/plat_sepolicy>
Output:
neverallow check failed at /out/soong/.intermediates/system/sepolicy/plat_pub_versioned.cil/android_common/plat_pub_versioned.cil:10810
  (neverallow base_typeattr_238_34_0 default_prop_34_0 (file (ioctl read write create setattr lock relabelfrom append unlink link rename open watch watch_mount watch_sb watch_with_perm wat>
    <root>
    allow at /out/soong/.intermediates/system/sepolicy/vendor_sepolicy.cil/android_common/vendor_sepolicy.cil:10022
      (allow hal_fingerprint_default default_prop_34_0 (file (read getattr map open)))

neverallow check failed at /out/soong/.intermediates/system/sepolicy/plat_sepolicy.cil/android_common/plat_sepolicy.cil:26055 from system/sepolicy/private/property.te:64
  (neverallow base_typeattr_238 base_typeattr_847 (file (ioctl read write create setattr lock relabelfrom append unlink link rename open watch watch_mount watch_sb watch_with_perm watch_re>
    <root>
    allow at /out/soong/.intermediates/system/sepolicy/vendor_sepolicy.cil/android_common/vendor_sepolicy.cil:10022
      (allow hal_fingerprint_default default_prop_34_0 (file (read getattr map open)))

neverallow check failed at /out/soong/.intermediates/system/sepolicy/plat_sepolicy.cil/android_common/plat_sepolicy.cil:15448 from system/sepolicy/public/property.te:259
  (neverallow base_typeattr_238 default_prop (file (ioctl read write create setattr lock relabelfrom append unlink link rename open watch watch_mount watch_sb watch_with_perm watch_reads)))
    <root>
    allow at /out/soong/.intermediates/system/sepolicy/vendor_sepolicy.cil/android_common/vendor_sepolicy.cil:10022
      (allow hal_fingerprint_default default_prop_34_0 (file (read getattr map open)))

Failed to generate binary
Failed to build policydb

Signed-off-by: TogoFire <togofire@mailfence.com>
Change-Id: I2af87c54c1d70b0b2f61b88a311c7aad4a05c323